### ISSUE TITLE
Macros that are used in defconstant need to be eval-when compile

### ISSUE THREAD

**Issue by Yehouda** [ralph-schleicher/codata-recommended-values#2]
https://github.com/ralph-schleicher/codata-recommended-values/blob/d776c4495766098bfaac0f1745220c736689d9f3/codata-2022.lisp#L42

This defmacro needs to be wrapped by **(eval-when (compile load eval) ..**, otherwise the compiler is not supposed to know about it when calling the evaluator, which it does when compiling defconsant. 
At least LispWorks error on this. 
It works if you load the source first, but not when just compiling. 
Same in codata-2018.lisp, codata-2014.isp, codata-2010.lisp.

**Comment by ralph-schleicher** [comment]
Thanks for the report. The bug is fixed in version 20241211.1602.
